### ISSUE TITLE
Max recursion depth exceeded

### ISSUE THREAD

**Issue by IanCZane** [slush0/stratum#19]
When I try to install this, using either `sudo python setup.py develop` or `sudo python setup.py develop`, I get a `max recursion depth exceeded` error.  Anything you suggest?  I've tried adding `sys.setrecursionlimit(5000)` to the beginnings of various files (after the `import` calls, of course), but I'm still hitting the limit.  I'm thinking it might be an issue of RAM, as I don't have much, but that seems like a pretty weird issue for me to be having.  It'd be pretty odd for a python module installation to use more than a few megabytes of RAM, right?

I'm trying to install using Python 2.7.6 on Ubuntu 14.04.

Edit: This is still technically an issue, but it isn't in any way urgent, as I was able to get the proxy running on my VPS via Wine.  It doesn't work with Mono, but it does with Wine.

**Comment by EvgenijM86** [comment]
I can confirm that commenting those 2 lines fixes this problem.

**Comment by asansi** [comment]
Any idea what might have caused this?  I'm having the same issue, even after removing those 2 lines.
