### ISSUE TITLE
Python dev protect us from ourselves

### ISSUE THREAD

**Issue by gigafunk** [slush0/stratum#26]
So I cant install stratum because an 0ct  2017 commit of python disabled http in favor of https. So it complains 

urllib2.HTTPError: HTTP Error 403: SSL is required

at the end of not being able to find files.  
I tried adding an S to the http link in the setup.py script, but the source has no cert I guess.

PS "Let's Encrypt" is amazing and free way to add a cert to a site if you have any control over that side of this

**Comment by CephalopodLuke** [comment]
Have you read the topic below?

https://github.com/Crypto-Expert/stratum-mining/wiki/Getting-Started-With-Stratum

**Comment by gigafunk** [comment]
Yes. I fail to see where it mentions a workaround for the python change in October that dropped support for non SSL sites. Am I missing something? I think this is a new issue and it cannot be built with a current version of python now.

**Comment by kaskii** [comment]
@gigafunk Did you resolve this issue?

**Comment by gigafunk** [comment]
Nope, I moved on. I was just setting up a personal pool for my various mixed hardware, fooling around. Thanks for checking in, sry I missed this.

**Comment by ahmedbodi** [comment]
this was resolved in my version
